name: Deploy Portfolio to IONOS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: su526944
          password: ${{ secrets.IONOS_PASS }}
          port: 22
          source: "./*"
          target: "/portfolio/"
          timeout: 60s
          overwrite: true
